name: Audit
on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  security_audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4
      - name: Check | Audit
        uses: rustsec/audit-check@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
